apiVersion: apps/v1
kind: Deployment
metadata:
  name: ci-cd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ci-cd-demo
  template:
    metadata:
      labels:
        app: ci-cd-demo
    spec:
      containers:
      - name: app
        image: <DOCKER_IMAGE>
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ci-cd-demo
spec:
  selector:
    app: ci-cd-demo
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
